apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-catalog-deployment
  labels:
    app: ms-catalog
    tier: backend
    environment: production
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-catalog
      version: v1
  template:
    metadata:
      labels:
        app: ms-catalog
        version: v1
    spec:
      containers:
        - name: ms-catalog-pod
          image: docker.io/guilhermegoncalvess/ms-catalog
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ms-catalog-service
spec:
  selector:
    app: ms-catalog
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-catalog-config-map
data:
  MS_NAME: 'ms-catalog'
  NODE_ENV: 'production'
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-catalog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-catalog-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
