apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-catalog
  name: ms-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-catalog
    spec:
      containers:
        - image: gcr.io/learning-357114/ms-catalog:1.0.0
          name: ms-catalog
          resources: {}
          imagePullPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ms-catalog
spec:
  type: NodePort
  selector:
    app: ms-catalog
  ports:
  - protocol: TCP
    port: 3333
    targetPort: 3333
---
